name: deploy-workflow
on: 
  workflow_dispatch:
    inputs:
      model_path:
        description: 'Deploy new model path'     
        required: true
        default: 'None'

jobs:
  deploy-workflow:
    name: deploy-model 
    runs-on: ubuntu-latest
    environment: 'prod'
    container:
      image: mlrun/mlrun:1.4.1
      options: --user 1001
      
    steps: 
    - uses: actions/checkout@v2
    - name: deploy the new model
      run: |
        python -m mlrun project ./ --run deploy \
        --secrets env=MY_GITHUB_TOKEN \
        --git-repo ${GITHUB_REPOSITORY} \
        --watch \
        --arguments model_path=${{ github.event.inputs.model_path }}
      env:
        V3IO_USERNAME: ${{ secrets.V3IO_USERNAME }}
        V3IO_PASSWORD: ${{ secrets.V3IO_USERNAME }}
        V3IO_API: ${{ secrets.V3IO_API }}
        V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
        MLRUN_DBPATH: ${{ secrets.MLRUN_DBPATH }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} 
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        CMD: ${{ github.event.comment.body}}  
        COMMIT: ${{ github.sha}}
