name: training-workflow
on: 
  workflow_dispatch:
    inputs:
      existing_model_path:
        description: 'Model path of existing model for comparison'     
        required: false
        default: 'None'

jobs:
  training-workflow:
    name: training-model
    runs-on: ubuntu-latest
    environment: 'qa'
    container:
      image: mlrun/mlrun:1.4.1
      options: --user 1001
      
    steps:
    - uses: actions/checkout@v2
    - name: Training model

      run: |
        python -m mlrun project ./ --run train \
        --secrets env=MY_GITHUB_TOKEN \
        --git-repo ${GITHUB_REPOSITORY} \
        --git-issue 1 \
        -w -x commit=${COMMIT:33} \
        -a existing_model_path=${{ github.event.inputs.existing_model_path}} \
        -a force_deploy=true
      env:
        V3IO_USERNAME: ${{ secrets.V3IO_USERNAME }}
        V3IO_PASSWORD: ${{ secrets.V3IO_USERNAME }}
        V3IO_API: ${{ secrets.V3IO_API }}
        V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
        MLRUN_DBPATH: ${{ secrets.MLRUN_DBPATH }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} 
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        CMD: ${{ github.event.comment.body}}  
        COMMIT: ${{ github.sha}}
